import media
import fresh_tomatoes

# These instances each represents a movie and will be displayed 
#on the page generated by fresh_tomatoes.py.
#The parameters between parenthesis are the following: movie title, 
#story line, movie poster, link to the trailer
# and main actors.

toy_story = media.Movie("Toy Story",
                        "A story of a boy and his toys that come to life",
                        "http://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg"  # noqa
                        ,
                        "https://www.youtube.com/watch?v=vwyZH85NQC4",
                        "Andy, Buzz, Woody")

avatar = media.Movie("Avatar",
                     "A marine on an alien planet",
                     "https://lh3.googleusercontent.com/-rf4DkJzNcLI/VZ7-G6Ejt2I/AAAAAAAABrI/0MYWo7PP1tg/w1215-h1600/Avatar.jpg"  # noqa
                     ,
                     "http://www.youtube.com/watch?v=-9ceBgWV8io",
                     "A marine, blue guys, weird animals")

trainspotting = media.Movie("Trainspotting",
                            "Heroine and drugs. Redemption.",
                            "https://upload.wikimedia.org/wikipedia/en/7/71/Trainspotting_ver2.jpg"  # noqa
                            ,
                            "https://www.youtube.com/watch?v=R2GKVtWsXKY",
                            "Ewan McGregor, Junkie number 1, Junkie number 2")

trainspotting1 = media.Movie("Trainspotting",
                            "Heroine and drugs. Redemption.",
                            "https://upload.wikimedia.org/wikipedia/en/7/71/Trainspotting_ver2.jpg"  # noqa
                            ,
                            "https://www.youtube.com/watch?v=R2GKVtWsXKY",
                            "Ewan McGregor, Junkie number 1, Junkie number 2")

trainspotting2 = media.Movie("Trainspotting",
                            "Heroine and drugs. Redemption.",
                            "https://upload.wikimedia.org/wikipedia/en/7/71/Trainspotting_ver2.jpg"  # noqa
                            ,
                            "https://www.youtube.com/watch?v=R2GKVtWsXKY",
                            "Ewan McGregor, Junkie number 1, Junkie number 2" )

trainspotting3 = media.Movie("Trainspotting",
                            "Heroine and drugs. Redemption.",
                            "https://upload.wikimedia.org/wikipedia/en/7/71/Trainspotting_ver2.jpg"  # noqa
                            ,
                            "https://www.youtube.com/watch?v=R2GKVtWsXKY",
                            "Ewan McGregor, Junkie number 1, Junkie number 2")

movies = [toy_story, avatar, trainspotting, trainspotting1,
          trainspotting2, trainspotting3]

#This command calls the function open_movies_page
#located in fresh_tomatoes.py, which generates
#our webpage.

fresh_tomatoes.open_movies_page(movies)

print (media.Movie.VALID_RATINGS)
